python_modules: do tcpconn metric collection in a blocking mode
As reported by Kostas Georgiou in BUG196 :

  http://bugzilla.ganglia.info/cgi-bin/bugzilla/show_bug.cgi?id=196

there is no need to use poll if processing the netstat output will be
done synchronously.

this simplifies the logic and reduces the probability of an uncatched
exception killing the python collection thread as shown by :

  Exception in thread Thread-1:
  Traceback (most recent call last):
  File "python2.5/threading.py", line 460, in __bootstrap self.run()
  File "ganglia/python_modules/tcpconn.py", line 252, in run poll_events = fd_poll.poll()
    error: (4, 'Interrupted system call')

the fix from Kostas also speedups the shutdown by skipping the sleep


git-svn-id: http://ganglia.svn.sourceforge.net/svnroot/ganglia/trunk/monitor-core@1621 93a4e39c-3214-0410-bb16-828d8e3bcd0f