gmetad: workaround broken apr-1 headers depending incorrectly on off64_t
since r2106, APR was added as a dependency for gmetad and therefore
this workaround had to be applied here as well, or will otherwise
result in a broken build in at least 32bit linux as shown by :

  In file included from /usr/include/apr-1/apr.h:7,
                   from /usr/include/apr-1/apr_time.h:25,
                   from gmetad.c:14:
  /usr/include/apr-1/apr-i386.h:285: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'apr_off_t'


git-svn-id: http://ganglia.svn.sourceforge.net/svnroot/ganglia/trunk/monitor-core@2188 93a4e39c-3214-0410-bb16-828d8e3bcd0f