include: protect unsuspecting module users against apr 1.0 header bug
apr.h relies in off64_t being defined, failing in 32bit platforms with:

  /usr/include/apr-1.0/apr.h:273: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'apr_off_t'


git-svn-id: http://ganglia.svn.sourceforge.net/svnroot/ganglia/trunk/monitor-core@1488 93a4e39c-3214-0410-bb16-828d8e3bcd0f